default: &default
  adapter: postgresql
  encoding: unicode
  # Here we make sure we can pass the connection URL for the database
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ragrp_development

test:
  <<: *default
  database: ragrp_test

production:
  <<: *default
  adapter: postgresql
  host: db
  database: ragrp_production
  username: ragrp
  password:
